# Config file of the project

# Defining the default working directory
workdir : /students/2023-2024/Thema11/mvandestreek_snakemake/BioinfDataprocessingExercises/SRRsSnakeMakePipeline
samples_directory : /students/2023-2024/Thema11/mvandestreek_snakemake/samples/
rRNA_databases : /students/2023-2024/Thema11/mvandestreek_snakemake/BioinfDataprocessingExercises/SRRsSnakeMakePipeline/sortme_references/

# Samples
accessions :
  - SS
  #- sample1
  #- SRR2541811

threads : 30
memory_gb : 64


