# -------- Configuration file for the SnakeMake pipeline --------

# -------- Working directory path --------
# The path to the working directory where the pipeline will be executed
# This path must be an absolute path to the root of the folder. No slash (/) at the end of the path.
# Make sure, the path ends not in tutorial 01 or tutorial 02, but SRRsSnakeMakePipeline
# Example: /home/user/BioinfDataprocessingExercises/SRRsSnakeMakePipeline
workdir : /students/2023-2024/Thema11/mvandestreek_snakemake/BioinfDataprocessingExercises/SRRsSnakeMakePipeline

# -------- Path where the samples are stored --------
# Make sure, the path ends in with an / (slash)
# Example: /home/user/BioinfDataprocessingExercises/SRRsSnakeMakePipeline/samples/
samples_directory : /students/2023-2024/Thema11/mvandestreek_snakemake/samples/

# -------- Path where the references are stored --------
# You could create a custom folder in the BioinfDataprocessingExercises/SRRsSnakeMakePipeline folder,
# and change the path to the created folder.
rRNA_databases : /sortme_references/

# -------- Samples / accessions numbers --------
accessions :
  #- <Input accession numbers below>
  - SRR2541811

# -------- Technical properties --------
# The number of threads to use for the pipeline
# The amount of memory to use for the pipeline, in gigabytes
# Make sure you use the correct values for your system, otherwise the pipeline will fail
threads : 30
memory_gb : 250
