# Config file of the project

# Defining the default working directory
workdir : /homes/mvandestreek/HANZEHOGESCHOOL_GRONINGEN/2023-2024/thema11/dataprocessing/BioinfDataprocessingExercises/SRRsSnakeMakePipeline
samples_directory : /homes/mvandestreek/

# Samples
samples :
  - SS
  #- sample1
  #- SRR2541811

threads : 20


