"""
Snakefile where you can find the first simple workflow pipeline. 
This pipeline is composed of multiple rules. See the
"""
configfile: "config/config.yaml",
workdir: "/Users/mvandestreek/Library/CloudStorage/OneDrive-HanzehogeschoolGroningen/HanzeHogeschool/2023-2024/thema11/dataprocessing/BioinfDataprocessingExercises/tutorial_02/",
# url = "https://bioinf.nl/~ronald/snakemake/",
url = "bioinf.nl/~ronald/snakemake/WC03/data/"
# sample = "test"

# WERKT NIET
rule all:
    input:
        "merged.bam"

rule download:
    output:
        "{sample}.bam"
    shell:
        "wget {url}{output}"

rule samtools_merge:
    input:
        expand("{sample}.bam", sample=config["samples"])
    output:
        "merged.bam"
    wrapper:
        "v3.4.0/bio/samtools/merge"

# WERKT WEL
# rule all:
#     input:
#         expand("{sample}.bam", sample=config["samples"])

# rule download:
#     output:
#         "{sample}.bam"
#     shell:
#         "wget {url}{output}"