"""
The main file of this project. All the rules will be imported from seperate files.
Goal: 
    Create a de novo assembly from paired end sequences with quality assesments
Author: 
    Mark van de Streek
Date: 
    2024-03-16
Copyright: 
    BFV3 2023-2024
"""

configfile: "config/config.yaml",
workdir: config['workdir'],

rule all:
    input:
        expand("results/{sample}_fastqc.html", sample=config['samples']),
        expand("results/{sample}_fastqc.zip", sample=config['samples']),

include: "rules/dataAccesion.smk"
include: "rules/FastqcRun.smk"
