# Config file of the project

# Defining the default working directory
workdir : /homes/mvandestreek/HANZEHOGESCHOOL GRONINGEN/2023-2024/thema11/dataprocessing/BioinfDataprocessingExercises/eindopdracht

# Samples
samples :
  - SRR2541813
